name: Auto Assign

on:
  pull_request:
    types: [ opened ]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Auto-assign PR
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
          numOfAssignee: 1
